name: clear_current_data_immediate

on: [workflow_dispatch, workflow_call]

jobs:
  clear_current_data_immediate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: true  # Allows push access for the commit

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Clear plant data for today and for current month
      working-directory: action_helpers
      run: |
        python clear_current_data.py

    - name: Update repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add plant_data/
        git commit -m "Clear current data" -a || echo "No changes to commit"
        git push
