name: get_current_data_cron

on:
  schedule:
    # every 15 minutes
    - cron: '*/15 * * * *'

jobs:
  get_current_data_cron:
    uses: ./.github/workflows/get_current_data_immediate.yaml
    secrets:
      SHINEPHONE_USERNAME: ${{ secrets.SHINEPHONE_USERNAME }}
      SHINEPHONE_PASSWORD: ${{ secrets.SHINEPHONE_PASSWORD }}
