name: store-growatt-ids

on: [workflow_dispatch]

jobs:
  store-growatt-ids:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: true  # Allows push access for the commit

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      working-directory: action_helpers
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Extract credentials into environment variables
      working-directory: action_helpers
      env:
        SHINEPHONE_USERNAME: ${{ secrets.SHINEPHONE_USERNAME }}
        SHINEPHONE_PASSWORD: ${{ secrets.SHINEPHONE_PASSWORD }}
      run: |
        echo "GROWATT_USER_ID=$(python get_user_id.py)" >> $GITHUB_ENV
        echo "GROWATT_PLANT_ID=$(python get_plant_ids.py)" >> $GITHUB_ENV

    - name: Store IDs to file
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "GROWATT_USER_ID=${{ env.GROWATT_USER_ID }}" > plant_data/growatt.env
        echo "GROWATT_PLANT_ID=${{ env.GROWATT_PLANT_ID }}" >> plant_data/growatt.env
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add plant_data/growatt.env
        git commit -m "Store Growatt IDs" -a || echo "No changes to commit"
        git push
